export const FETCH_PRODUCT = 'FETCH_PRODUCT';
export const FETCH_PRODUCT_SUCCESS = 'FETCH_PRODUCT_SUCCESS';
export const FETCH_PRODUCT_FAILURE = 'FETCH_PRODUCT_FAILURE';

export const SHOW_LOADING_PRODUCT = 'SHOW_LOADING_PRODUCT';
export const HIDE_LOADING_PRODUCT = 'HIDE_LOADING_PRODUCT';
